### PR TITLE
Add support for custom opening and closing markers and custom fences (fixes #2)

### LINKED ISSUE #2: Support Front Matter with different opening and closing fences
In the [documentation for Hugo](https://gohugo.io/content-management/front-matter/) there's an example for JSON-formatted Front Matter which looks like this:

```
{
    "title": "spf13-vim 3.0 release and new website",
    "description": "spf13-vim is a cross platform distribution of vim plugins and resources for Vim.",
    "tags": [ ".vimrc", "plugins", "spf13-vim", "vim" ],
    "date": "2012-04-06",
    "categories": [
        "Development",
        "VIM"
    ],
    "slug": "spf13-vim-3-0-release-and-new-website"
}

# Title

Content
```

But this type of front matter uses only one instead of three marker characters for the fences, and the opening and closing fences aren't the same. So currently it can't be implemented as a custom "Matter" with just the `marker` property.

If there was a way to specify the full opening and closing string for the fence it would allow creating more different types of Front Matter, including JSON.

I was thinking something like this:

```js
{
  type: 'json',
  openingFence: '{',
  closingFence: '}',
}
```

or:

```js
{
  type: 'custom',
  openingFence: '<<<',
  closingFence: '>>>',
}
```

For backwards compatibility specifying just a `marker` could internally translate into ``openingFence = `${marker}${marker}${marker}` `` and ``closingFence = `${marker}${marker}${marker}` ``

For example:

```js
{
  type: 'yaml',
  marker: '-',
}
```

would become:

```js
{
  type: 'yaml',
  openingFence: '---',
  closingFence: '---',
}
```

### PR DESCRIPTION
**Pull request by maxkueng**
Adds support for Matters with different opening and closing markers as well as full fences, either as string or as object with separate opening and closing fences as discussed in #2.

I tried to keep the coding style as close as possible to the existing style, using `var` and little encapsulation. If I misinterpreted something I can fix it. Also `npm test` runs fine with 100% coverage.

The configuration options for custom Matters are extended to support the following cases:

```js
{ type: 'custom', marker: '-' }                         // ---\n...\n---
{ type: 'custom', marker: { open: '+', close: '-' } }   // +++\n...\n---
{ type: 'custom', fence: '=====' }                      // =====\n...\n=====
{ type: 'custom', fence: { open: '<<', close: '>>' } }  // <<\n...\n>>
```

In order to support the JSON syntax discussed in #2, however, there would have to be an additional option to preserve the fences in the tree.

The following document:

```
{
  "title": "My article",
  "tags": [ "cool", "awesome", "cute" ]
}

# Title

Content
```

Using the following Matter:

```js
{ type: 'json', fence: { open: '{', close: '}' } }
```

Would be missing the opening and closing curly brackets in the tree and therefore isn't valid JSON:

```
{
  "type": "root",
  "children": [
    {
      "type": "jsonml",
      "value": "  \"title\": \"My article\",\n  \"tags\": [ \"cool\", \"awesome\", \"cute\" ]",
      ...
```

I tried to implement `{ type: 'custom', preserveFences: true, fence: { open: '{', close: '}' } }` but then the fence appeared twice in the output of `proc.processSync(input)`. It was correct in the tree but not in the output of processing the document.

### CODE REVIEW

**Comment by wooorm** [comment]
From markdown’s perspective, the fences are indeed not part of the document.

`remark-frontmatter` just adds support for detecting it, parsing it, and compiling it back. It doesn’t actually parse YAML, TOML, or JSON, other plugins could do that. Is there any reason you couldn’t wrap `node.value` in `{}` before passing it to `JSON.parse` somewhere else?

**Comment by maxkueng** [comment]
Yeah, that's what I was planning on doing in case we don't find a solution to preserve the fences. In case of JSON I'd just ``JSON.parse(`{${node.value}}`) `` and it should be fine.

I know remark-frontmatter doesn't parse the YAML, TOML and JSON. In vmd I have a [separate plugin / transformer](https://github.com/yoshuawuyts/vmd/blob/f167729895f5cae94e5201f8a924e54d14dc3cb7/renderer/render-markdown.js#L199-L248) that then actually renders the content as a nested table, just like on GitHub, or as a code block, depending on what's set in the preferences.

Are you otherwise okay with the changes in this PR? Do you think it could be merged and released?

**Comment by wooorm** [comment]
Yes I’d accept it like this, but could you add docs for the new feature?

**Comment by maxkueng** [comment]
I've updated the README. I figured now that there are multiple ways to specify a `Matter` is makes sense to have some examples.

**Comment by wooorm** [comment]
Sweet! I refactored the readme a bit, and [also thought of a way to simplify the parser a lot](https://github.com/wooorm/remark-frontmatter/blob/0dee4b402b78247450e31ea42602124d52729f58/lib/parse.js#L18)!

**Comment by maxkueng** [comment]
Awesome, the parser looks much better now. I thought maybe there was a reason why you used `charAt()` to check every character individually and I didn't want to change  it too much. But it's great now!

Thanks a lot

**Comment by wooorm** [comment]
Yeah, I thought so too, but apparently this works fine :p

Thank \*you\* for working on this!

**Pull request closed without merging**
